/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Hoodie(props) {
  const { nodes, materials } = useGLTF('https://storage.googleapis.com/inceptivestudio/1671197530271.gltf ')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LTD_Hoodiev3.geometry} material={materials['Ape_3031 Low res']} />
    </group>
  )
}

useGLTF.preload('https://storage.googleapis.com/inceptivestudio/1671197530271.gltf ')
