// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/Tshirt.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes['t-shirt002'].geometry} material={materials['BAYC 3031']} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
//     </group>
//   )
// }

// useGLTF.preload('/Tshirt.gltf')
