/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mug(props) {
  const { nodes, materials } = useGLTF('https://storage.googleapis.com/inceptivestudio/1671197391314.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Ape 3031']} position={[0, -5, 0]} rotation={[Math.PI / 2, 0, 0]} scale={23.56} />
    </group>
  )
}

useGLTF.preload('https://storage.googleapis.com/inceptivestudio/1671197391314.gltf')
