/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useSelector } from "react-redux";

export default function Ape(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "https://storage.googleapis.com/inceptivestudio/1671197179830.gltf"
  );

  const { actions } = useAnimations(animations, group);
  const actionVal = useSelector((state) => state.action.name);
  useEffect(() => {
    if (actionVal) {
      var Mixer = actions[actionVal].getMixer();
      Mixer.stopAllAction();
      actions[actionVal].play();
    }
  }, [actionVal]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Ape"
            frustumCulled={false}
            geometry={nodes.Ape.geometry}
            material={materials.Ape1}
            skeleton={nodes.Ape.skeleton}
            castShadow={true}
          />
          <skinnedMesh
            name="Cap1"
            frustumCulled={false}
            geometry={nodes.Cap1.geometry}
            material={materials.Cap}
            skeleton={nodes.Cap1.skeleton}
            castShadow={true}
          />
          <skinnedMesh
            name="Cloth1"
            frustumCulled={false}
            geometry={nodes.Cloth1.geometry}
            material={materials.Cloth}
            skeleton={nodes.Cloth1.skeleton}
            castShadow={true}
          />
          <skinnedMesh
            name="Eyes"
            frustumCulled={false}
            geometry={nodes.Eyes.geometry}
            material={materials.Ape1}
            skeleton={nodes.Eyes.skeleton}
            castShadow={true}
          />
          <skinnedMesh
            name="Lower_Teeth"
            frustumCulled={false}
            geometry={nodes.Lower_Teeth.geometry}
            material={materials.Teeth}
            skeleton={nodes.Lower_Teeth.skeleton}
            castShadow={true}
          />
          <skinnedMesh
            name="Shoes1"
            frustumCulled={false}
            geometry={nodes.Shoes1.geometry}
            material={materials.Shoes}
            skeleton={nodes.Shoes1.skeleton}
            castShadow={true}
          />
          <skinnedMesh
            name="Upper_Teeth"
            frustumCulled={false}
            geometry={nodes.Upper_Teeth.geometry}
            material={materials.Teeth}
            skeleton={nodes.Upper_Teeth.skeleton}
            castShadow={true}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://storage.googleapis.com/inceptivestudio/1671197179830.gltf"
);
