/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const MODEL_URL =
  "https://storage.googleapis.com/inceptivestudio/1669703759686.gltf";

export default function Gang(props) {
  const { nodes, materials } = useGLTF(MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes.cc_base_hip} />
        <primitive object={nodes.ik_foot_r} />
        <primitive object={nodes.ik_foot_l} />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.belt.geometry}
          material={materials.Belt1}
          skeleton={nodes.belt.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.cat_body.geometry}
          material={materials.Cat_Body1}
          skeleton={nodes.cat_body.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.cat_cloths.geometry}
          material={materials.Cat_Cloths1}
          skeleton={nodes.cat_cloths.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.cat_eyes.geometry}
          material={materials.Cat_Eyes1}
          skeleton={nodes.cat_eyes.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.cat_neclace.geometry}
          material={materials.Cat_Neclace178}
          skeleton={nodes.cat_neclace.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.cat_teeth.geometry}
          material={materials.Cat_Teeth1}
          skeleton={nodes.cat_teeth.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.crown.geometry}
          material={materials.Crown1}
          skeleton={nodes.crown.skeleton}
          castShadow={true}
        />
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_URL);
