/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 Mayc.gltf
*/


import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useSelector } from "react-redux";

export default function Mayc(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "https://storage.googleapis.com/inceptivestudio/1672146207870.gltf"
  );

  const { actions } = useAnimations(animations, group);
  const actionVal = useSelector((state) => state.action.name);
  console.log(actions);
  useEffect(() => {
    if (actionVal) {
      var Mixer = actions[actionVal].getMixer();
      Mixer.stopAllAction();
      actions[actionVal].play();
    }
  }, [actionVal]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MAYC" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Bandage" geometry={nodes.Bandage.geometry} material={materials.Bandage} skeleton={nodes.Bandage.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Bandage_1" geometry={nodes.Bandage_1.geometry} material={materials.Bandage} skeleton={nodes.Bandage_1.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Cap" geometry={nodes.Cap.geometry} material={materials.cap} skeleton={nodes.Cap.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Cap_slime_remesh" geometry={nodes.Cap_slime_remesh.geometry} material={materials.Cap_slime} skeleton={nodes.Cap_slime_remesh.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Clothes" geometry={nodes.Clothes.geometry} material={materials.Clothes} skeleton={nodes.Clothes.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Clothes_1_remesh" geometry={nodes.Clothes_1_remesh.geometry} material={materials.Clothes} skeleton={nodes.Clothes_1_remesh.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Eyes" geometry={nodes.Eyes.geometry} material={materials.Eyes} skeleton={nodes.Eyes.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Face_base" geometry={nodes.Face_base.geometry} material={materials.Face_base} skeleton={nodes.Face_base.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Face_slime" geometry={nodes.Face_slime.geometry} material={materials.Face_slime} skeleton={nodes.Face_slime.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="farda_mesh1_Cilindro" geometry={nodes.farda_mesh1_Cilindro.geometry} material={materials.shorts} skeleton={nodes.farda_mesh1_Cilindro.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Intestines_remesh" geometry={nodes.Intestines_remesh.geometry} material={materials.Intestines} skeleton={nodes.Intestines_remesh.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="legs" geometry={nodes.legs.geometry} material={materials.legs} skeleton={nodes.legs.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="LIttle_zombie_remesh_remesh" geometry={nodes.LIttle_zombie_remesh_remesh.geometry} material={materials.LIttle_zombie} skeleton={nodes.LIttle_zombie_remesh_remesh.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Mask_remesh" geometry={nodes.Mask_remesh.geometry} material={materials.Mask} skeleton={nodes.Mask_remesh.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Mushrooms" geometry={nodes.Mushrooms.geometry} material={materials.Mushrooms} skeleton={nodes.Mushrooms.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="polySurface11" geometry={nodes.polySurface11.geometry} material={materials.Body} skeleton={nodes.polySurface11.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="Shoes" geometry={nodes.Shoes.geometry} material={materials.Old_Shoes} skeleton={nodes.Shoes.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="slimearm" geometry={nodes.slimearm.geometry} material={materials.sLIMEARM2} skeleton={nodes.slimearm.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="slimearm2" geometry={nodes.slimearm2.geometry} material={materials.sLIMEARM2} skeleton={nodes.slimearm2.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow={true} name="slimeleg" geometry={nodes.slimeleg.geometry} material={materials.legs} skeleton={nodes.slimeleg.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://storage.googleapis.com/inceptivestudio/1672146207870.gltf')
