/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

// *******************************************************************
// CONSTANTS

const MODEL_URL =
  "https://storage.googleapis.com/inceptivestudio/1667573030673.gltf";

export default function Renga(props) {
  const { nodes, materials } = useGLTF(MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.polySurface22001.geometry}
          material={materials.Samurai_1_Skull}
          skeleton={nodes.polySurface22001.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Samurai_3_Belongins1001.geometry}
          material={materials.Samurai_1_Belongins}
          skeleton={nodes.Samurai_3_Belongins1001.skeleton}
          castShadow={true}
        >
          <mesh
            frustumCulled={false}
            geometry={nodes.Samurai_1_Sword_Cover10.geometry}
            material={materials.Samurai_1_Sword}
            scale={0.01}
          />
        </skinnedMesh>
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Samurai_3_Body1001.geometry}
          material={materials.Samurai_1_Body}
          skeleton={nodes.Samurai_3_Body1001.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Samurai_3_Helmet001.geometry}
          material={materials.Samurai_1_Helmet}
          skeleton={nodes.Samurai_3_Helmet001.skeleton}
          castShadow={true}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Samurai_3_legs_n_hands3001.geometry}
          material={materials.Samurai_1_legs_n_hands}
          skeleton={nodes.Samurai_3_legs_n_hands3001.skeleton}
          castShadow={true}
        >
          <mesh
            frustumCulled={false}
            geometry={nodes.Samurai_2_Sword2.geometry}
            material={materials.Samurai_1_Sword}
            rotation={[0, 0, Math.PI / 2]}
            scale={0.01}
          />
        </skinnedMesh>
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Samurai_3_Skull2001.geometry}
          material={materials.Samurai_1_Skull}
          skeleton={nodes.Samurai_3_Skull2001.skeleton}
          castShadow={true}
        />
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_URL);
