/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

// *******************************************************************
// CONSTANTS

const MODEL_URL =
  "https://storage.googleapis.com/inceptivestudio/1667994619706.gltf";

// *******************************************************************

export default function Bedroom(props) {
  const { nodes, materials } = useGLTF(MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Backdrop_Backdrop_0.geometry}
        material={materials.Backdrop}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_1.geometry}
        material={materials.WindowFrame}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_2.geometry}
        material={materials.material}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_3.geometry}
        material={materials.Mattress}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_4.geometry}
        material={materials.Trim}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_5.geometry}
        material={materials.Fireplace}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_6.geometry}
        material={materials.Fire}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_7.geometry}
        material={materials.Carpet}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_8.geometry}
        material={materials.Pillows}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_9.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_10.geometry}
        material={materials.Drawer}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_11.geometry}
        material={materials.Sofa}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_12.geometry}
        material={materials.SofaPillows}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_13.geometry}
        material={materials.FloorLamp}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_14.geometry}
        material={materials["Trim.001"]}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_15.geometry}
        material={materials.Walls}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_16.geometry}
        material={materials.Ceiling}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_17.geometry}
        material={materials.Window}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_18.geometry}
        material={materials.PaintingFrame}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_19.geometry}
        material={materials.Floor}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_20.geometry}
        material={materials.FloorLight}
      />
      <mesh
        geometry={nodes.Backdrop_Backdrop_0_21.geometry}
        material={materials.Painting}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
