/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const MODEL_URL =
  "https://storage.googleapis.com/inceptivestudio/1667642968319.glb";

export default function Env(props) {
  const { nodes, materials } = useGLTF(MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane1.geometry}
        material={materials.Mat}
        position={[23.13, 135.02, -97.21]}
        rotation={[0, 1.57, 0]}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
