/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

// *******************************************************************
// CONSTANTS

const MODEL_URL =
  "https://storage.googleapis.com/inceptivestudio/1667979419234.gltf";

// *******************************************************************

export default function GridV2(props) {
  const { nodes, materials } = useGLTF(MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_1.geometry}
          material={materials.Mountains_Material_Emission}
        />
        <mesh
          geometry={nodes.Object_1_1.geometry}
          material={materials.Sun_Material_Emissions}
        />
        <mesh
          geometry={nodes.Object_1_2.geometry}
          material={materials["Gradient Wallpaper"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_URL);
