/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const MODEL_URL =
  "https://storage.googleapis.com/inceptivestudio/1669789500551.gltf";

export default function StudioPlane(props) {
  const { nodes, materials } = useGLTF(MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.ground.geometry}
        material={materials.ground}
        position={[0, -0.01, 0]}
        scale={[10, 10, 10]}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
